#!/usr/bin/env python3
"""The STR licensing gap: Inside Airbnb listings vs Austin's licensed STR registry.

Usage:  python scripts/analyze_str_gap.py          # writes docs/str-gap-findings.md

Reads raw_airbnb_listings (scripts/load_airbnb.py), raw_short_term_rentals and
district_boundary; writes the findings doc. Pure helpers below are import-safe
and unit-tested offline (tests/scripts/test_str_gap.py).
Data (c) Inside Airbnb (insideairbnb.com), CC BY 4.0.
"""
from __future__ import annotations

import logging
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))   # runnable as scripts/foo.py

from atx_dashboard.str_gap import compute_gap, md_table

log = logging.getLogger("atx.scripts.str_gap")

# --- analysis main (DB-touching; not unit-tested, per repo convention) -----

OUT = "docs/str-gap-findings.md"


def _pct(n, d) -> str:
    return f"{100.0 * n / d:.0f}%" if d else "n/a"


def run(conn) -> str:
    """Compute every figure and return the findings markdown."""
    g = compute_gap(conn)

    district_rows = [[f"D{row['district']}", row["active_n"], row["licensed_n"],
                      f"{row['active_n'] / row['licensed_n']:.1f}×" if row["licensed_n"] else "n/a"]
                     for row in g["by_district"]]

    # tables precomputed as locals — md_table(...) calls with quoted args inside
    # f-string expressions are a SyntaxError below Python 3.12
    cls = g["license_classes"]
    license_tbl = md_table(
        ["License field", "Listings", "% of active"],
        [["Blank / missing", cls["missing"], _pct(cls["missing"], g["active"])],
         ["Claims exempt", cls["exempt"], _pct(cls["exempt"], g["active"])],
         ["Claims a number", cls["claims_number"], _pct(cls["claims_number"], g["active"])],
         ["— of which verified in registry", cls["verified"], _pct(cls["verified"], g["active"])],
         ["Other text", cls["other"], _pct(cls["other"], g["active"])]])
    district_tbl = md_table(
        ["District", "Active Airbnb listings", "Licensed STRs", "Ratio"], district_rows)
    zip_tbl = md_table(
        ["ZIP", "Active Airbnb listings", "Licensed STRs"],
        [[row["zip"], row["active_n"], row["licensed_n"]] for row in g["by_zip"]])
    host_tbl = md_table(
        ["Host size", "Listings", "% of active"],
        [["Host has 2+ listings", g["hosts"]["multi2"], _pct(g["hosts"]["multi2"], g["active"])],
         ["Host has 5+ listings", g["hosts"]["multi5"], _pct(g["hosts"]["multi5"], g["active"])],
         ["Host has 10+ listings", g["hosts"]["multi10"], _pct(g["hosts"]["multi10"], g["active"])]])

    # License-field note is data-driven: earlier snapshots carried no license text at all,
    # but Airbnb began surfacing a license field for Austin — so state what THIS snapshot shows.
    claims, verified, missing = cls["claims_number"], cls["verified"], cls["missing"]
    if claims:
        license_note = (
            f"*Note (snapshot {g['snapshot_date']}): {claims:,} active listings "
            f"({_pct(claims, g['active'])}) display a license number and {verified:,} "
            f"({_pct(verified, g['active'])}) match a case number in the city registry. This is a "
            f"change from the 2025-09 snapshot, which carried no license text on any listing. The "
            f"remaining {missing:,} ({_pct(missing, g['active'])}) show no license — but a blank "
            f"field is not itself proof of non-compliance (an operator may be licensed and simply "
            f"not enter the number).*"
        )
    else:
        license_note = (
            "*Note: this snapshot carries NO license text on any listing — per-listing "
            "verification against the registry is impossible from the listing side, so the gap "
            "analysis rests on aggregate counts and geography.*"
        )

    return f"""# The STR licensing gap — findings

*Generated by `scripts/analyze_str_gap.py` from the Inside Airbnb {g["snapshot_date"]} Austin snapshot
and the live STR registry ({g["licensed_n"]:,} licenses). Research, not advocacy.*

## The gap

Airbnb alone lists **{g["total"]:,}** Austin short-term rentals, of which **{g["active"]:,}**
were reviewed in the last 12 months (recently active) — against **{g["licensed_n"]:,}** licensed
STRs in the city registry. Roughly **{g["active"] / g["licensed_n"]:.1f}×** more recently-active
Airbnb listings than licenses of any type. {g["entire"]:,} of the active listings
({_pct(g["entire"], g["active"])}) are entire homes.

Restricting to listings that geolocate inside the 10 council districts — the city's licensing
jurisdiction — the comparison is **{g["in_district"]:,}** active listings vs **{g["licensed_n"]:,}**
licenses (**{g["in_district"] / g["licensed_n"]:.1f}×**).

## License compliance (active listings)

{license_tbl}

{license_note}

## Where — operating vs licensed, by council district

{district_tbl}

*{g["unlocated"]} active listings ({_pct(g["unlocated"], g["active"])}) geolocate outside all 10 council
districts — Inside Airbnb's "Austin" export spans the metro area (Lakeway, Round Rock,
unincorporated Travis/Hays Co.), wider than city licensing jurisdiction. They are excluded
from the district table above.*

### Top ZIPs (secondary cut — Airbnb's neighbourhood field is a ZIP)

{zip_tbl}

## Who — host concentration (active listings)

{host_tbl}

## Methodology

Operating universe is the Inside Airbnb Austin summary snapshot ({g["snapshot_date"]}); "recently active"
means at least one review in the trailing 12 months (number_of_reviews_ltm >= 1 — Inside
Airbnb's own activity convention). Licensed universe is the city STR registry
(raw_short_term_rentals, {g["licensed_n"]:,} rows). License verification normalizes the
host-entered license field and the registry case_number to their digit sequences and
matches exactly. District assignment is point-in-polygon of the listing's coordinates
against the city district boundaries (pure-Python, same code as the parcel crosswalk).

## Caveats

- Airbnb only — no VRBO or other platforms, so the operating count is still a FLOOR.
- Inside Airbnb anonymizes listing locations by up to ~150m — fine at district grain.
- Snapshot date ({g["snapshot_date"]}) differs from the registry pull date; both are recent, not same-day.
- The license field is host-self-reported; "claims a number" is not verification by itself.
- Some listings are hotels/boutique properties licensed under other regimes.
- A host's listings may include units outside Austin's licensing jurisdiction.
- Inside Airbnb's "Austin" scope is the metro area, wider than city limits — the headline
  counts include listings outside Austin's licensing jurisdiction; the in-district figures
  are the jurisdiction-fair comparison.

## Sources

- Inside Airbnb (insideairbnb.com), Austin snapshot {g["snapshot_date"]} — data licensed CC BY 4.0.
- City of Austin STR registry (raw_short_term_rentals), district boundaries (city GeoJSON).
"""


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s %(message)s")
    from atx_dashboard import db   # local import keeps pure helpers import-safe offline
    with db.connect() as conn:
        report = run(conn)
    with open(OUT, "w", encoding="utf-8") as f:
        f.write(report)
    log.info("wrote %s", OUT)


if __name__ == "__main__":
    main()
